# name: Test Coverage

# on: [push]


# jobs:
#   run-linters:
#     runs-on: macos-latest
#     steps:
#       - name: Run tests
#         run: swift test --enable-code-coverage

#       - name: Test coverage
#         uses: maxep/spm-lcov-action@0.3.0
#         with:
#           output-file: ./coverage/lcov.info

name: Try comment on PR

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      # - name: Coverage comment
      #   uses: kuju63/coverage-comment
      #   with:
      #     token: ${{ github.token }}
      #     paths: coverage/coverage-summary.xml
      #     type: 'cobertura'
      #     debug: '0'

        