name: Test Coverage

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      # - name: Build and Test
      #   run:  xcodebuild -workspace iOS/Template.xcworkspace -scheme AllUnitTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.2' -enableCodeCoverage YES test
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1.2.1
      - name: Build and Test
        run: swift test --enable-code-coverage
      - name: Test coverage
        uses: maxep/spm-lcov-action@0.3.0
        with:
          output-file: ./coverage/lcov.info
          file-format: text
      - name: report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info

        