# name: Test Coverage

# on: [push]


# jobs:
#   run-linters:
#     runs-on: macos-latest
#     steps:
#       - name: Run tests
#         run: swift test --enable-code-coverage

#       - name: Test coverage
#         uses: maxep/spm-lcov-action@0.3.0
#         with:
#           output-file: ./coverage/lcov.info

name: Test Coverage Report

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild -project iOS/Template.xcodeproj -scheme Template -sdk iphonesimulator -destination 'platform=iOS Simulator, name=Any iOS Simulator Device' -enableCodeCoverage YES test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
      # - name: Build and Test
      #   run: swift test --enable-code-coverage --skip-build --show-codecov-path
      # - name: Test coverage
      #   uses: maxep/spm-lcov-action@0.3.0
      #   with:
      #     output-file: ./coverage/lcov.info

        