# name: Test Coverage

# on: [push]


# jobs:
#   run-linters:
#     runs-on: macos-latest
#     steps:
#       - name: Run tests
#         run: swift test --enable-code-coverage

#       - name: Test coverage
#         uses: maxep/spm-lcov-action@0.3.0
#         with:
#           output-file: ./coverage/lcov.info

name: Test Coverage Report

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Test coverage
        uses: kuju63/coverage-comment
        with:
          token: ${{ github.token }}
          paths: coverage/coverage-summary.xml
          type: 'cobertura'
          debug: '0'

        